#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MeetMeet_Native_Portable.Droid.Resource", IsApplication=true)]

namespace MeetMeet_Native_Portable.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int buttonSize = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int colorScheme = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int scopeUris = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int common_action_bar_splitter = 2130968584;
			
			// aapt resource value: 0x7f040011
			public const int common_google_signin_btn_text_dark = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_dark_default = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_signin_btn_text_dark_disabled = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_signin_btn_text_dark_focused = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_signin_btn_text_dark_pressed = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int common_google_signin_btn_text_light = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_signin_btn_text_light_default = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_signin_btn_text_light_disabled = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_google_signin_btn_text_light_focused = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_signin_btn_text_light_pressed = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_plus_signin_btn_text_dark = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int common_plus_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_plus_signin_btn_text_dark_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_plus_signin_btn_text_dark_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_plus_signin_btn_text_dark_pressed = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int common_plus_signin_btn_text_light = 2130968596;
			
			// aapt resource value: 0x7f040004
			public const int common_plus_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_plus_signin_btn_text_light_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_plus_signin_btn_text_light_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_plus_signin_btn_text_light_pressed = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_disabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_pressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_disabled = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_ic_googleplayservices = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_dark_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_disabled = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_focused = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_light_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_light_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_disabled = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_focused = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_dark_normal = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_dark_pressed = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_disabled = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_focused = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_light_normal = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_light_pressed = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int edit_text_style = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_stat_ic_notification = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Icon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ProgressBarStyle = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int rec_msg = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int sent_msg = 2130837553;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f080022
			public const int BtnAcptMeetInvitation = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int BtnDeclineMeetInvitation = 2131230755;
			
			// aapt resource value: 0x7f080021
			public const int BtnInviteCheckProfile = 2131230753;
			
			// aapt resource value: 0x7f080034
			public const int MeetMeet = 2131230772;
			
			// aapt resource value: 0x7f08001a
			public const int NearbyUsersButton = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int RelativeLayout01 = 2131230744;
			
			// aapt resource value: 0x7f08001d
			public const int SendMessageButton = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int SetLocationButton = 2131230748;
			
			// aapt resource value: 0x7f080035
			public const int SignInButton = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int SignUpButton = 2131230774;
			
			// aapt resource value: 0x7f080025
			public const int TextView01 = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int TextView02 = 2131230758;
			
			// aapt resource value: 0x7f080028
			public const int TextView03 = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int TextView04 = 2131230761;
			
			// aapt resource value: 0x7f08002b
			public const int TextView05 = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int TextView06 = 2131230764;
			
			// aapt resource value: 0x7f08002e
			public const int TextView07 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int TextView08 = 2131230767;
			
			// aapt resource value: 0x7f080031
			public const int TextView09 = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int TextView10 = 2131230770;
=======
			// aapt resource value: 0x7f080024
			public const int BtnAcptMeetInvitation = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int BtnDeclineMeetInvitation = 2131230757;
			
			// aapt resource value: 0x7f080023
			public const int BtnInviteCheckProfile = 2131230755;
			
			// aapt resource value: 0x7f080036
			public const int MeetMeet = 2131230774;
			
			// aapt resource value: 0x7f08001c
			public const int NearbyUsersButton = 2131230748;
			
			// aapt resource value: 0x7f08001a
			public const int RelativeLayout01 = 2131230746;
			
			// aapt resource value: 0x7f08001f
			public const int SendMessageButton = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int SetLocationButton = 2131230750;
			
			// aapt resource value: 0x7f080037
			public const int SignInButton = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int SignUpButton = 2131230776;
			
			// aapt resource value: 0x7f080027
			public const int TextView01 = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int TextView02 = 2131230760;
			
			// aapt resource value: 0x7f08002a
			public const int TextView03 = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int TextView04 = 2131230763;
			
			// aapt resource value: 0x7f08002d
			public const int TextView05 = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int TextView06 = 2131230766;
			
			// aapt resource value: 0x7f080030
			public const int TextView07 = 2131230768;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f080031
			public const int TextView08 = 2131230769;
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f08001f
			public const int UsernameInviteTextView = 2131230751;
			
			// aapt resource value: 0x7f080019
			public const int UsernameTextView = 2131230745;
=======
			// aapt resource value: 0x7f080033
			public const int TextView09 = 2131230771;
			
			// aapt resource value: 0x7f080034
			public const int TextView10 = 2131230772;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f080044
			public const int UserProfile = 2131230788;
			
			// aapt resource value: 0x7f080021
			public const int UsernameInviteTextView = 2131230753;
			
			// aapt resource value: 0x7f08001b
			public const int UsernameTextView = 2131230747;
			
			// aapt resource value: 0x7f080006
			public const int adjust_height = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int adjust_width = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int auto = 2131230723;
			
			// aapt resource value: 0x7f080046
			public const int bioviewprofile = 2131230790;
			
			// aapt resource value: 0x7f08004c
			public const int blockViewProfileButton = 2131230796;
			
			// aapt resource value: 0x7f080012
			public const int btnDialogEmail = 2131230738;
			
			// aapt resource value: 0x7f08000e
			public const int btnDialogSignIn = 2131230734;
			
			// aapt resource value: 0x7f080019
			public const int btnEditProfileSave = 2131230745;
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f08001e
			public const int btnGroupMessage = 2131230750;
=======
			// aapt resource value: 0x7f080020
			public const int btnGroupMessage = 2131230752;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f08000b
			public const int btnSendMsg = 2131230731;
			
			// aapt resource value: 0x7f080016
			public const int closeMsgButton = 2131230742;
			
			// aapt resource value: 0x7f080004
			public const int dark = 2131230724;
			
			// aapt resource value: 0x7f080050
			public const int deleteUser = 2131230800;
			
			// aapt resource value: 0x7f08004a
			public const int downvoteButton = 2131230794;
			
			// aapt resource value: 0x7f08004f
			public const int editProfile = 2131230799;
			
			// aapt resource value: 0x7f080009
			public const int editsenduser = 2131230729;
			
			// aapt resource value: 0x7f080017
			public const int edittextgender = 2131230743;
			
			// aapt resource value: 0x7f08000a
			public const int edittextmsg = 2131230730;
			
			// aapt resource value: 0x7f080018
			public const int edittextprofile = 2131230744;
			
			// aapt resource value: 0x7f08003e
			public const int fragment1 = 2131230782;
			
			// aapt resource value: 0x7f080000
			public const int icon_only = 2131230720;
			
			// aapt resource value: 0x7f080042
			public const int imageButton1 = 2131230786;
			
			// aapt resource value: 0x7f08003f
			public const int imageView1 = 2131230783;
			
			// aapt resource value: 0x7f08004b
			public const int inviteViewProfileButton = 2131230795;
			
			// aapt resource value: 0x7f080005
			public const int light = 2131230725;
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f080024
			public const int linearLayout1 = 2131230756;
			
			// aapt resource value: 0x7f080027
			public const int linearLayout2 = 2131230759;
			
			// aapt resource value: 0x7f08002a
			public const int linearLayout3 = 2131230762;
			
			// aapt resource value: 0x7f08002d
			public const int linearLayout4 = 2131230765;
			
			// aapt resource value: 0x7f080030
			public const int linearLayout5 = 2131230768;
=======
			// aapt resource value: 0x7f080026
			public const int linearLayout1 = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int linearLayout2 = 2131230761;
			
			// aapt resource value: 0x7f08002c
			public const int linearLayout3 = 2131230764;
			
			// aapt resource value: 0x7f08002f
			public const int linearLayout4 = 2131230767;
			
			// aapt resource value: 0x7f080032
			public const int linearLayout5 = 2131230770;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f08004e
			public const int logout = 2131230798;
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f080033
			public const int msgText = 2131230771;
=======
			// aapt resource value: 0x7f080035
			public const int msgText = 2131230773;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f080043
			public const int nearby_users_fragment = 2131230787;
			
			// aapt resource value: 0x7f080048
			public const int negativevoteviewprofile = 2131230792;
			
			// aapt resource value: 0x7f080008
			public const int none = 2131230728;
			
			// aapt resource value: 0x7f080047
			public const int positivevoteviewprofile = 2131230791;
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f080038
			public const int progressBar1 = 2131230776;
=======
			// aapt resource value: 0x7f08003a
			public const int progressBar1 = 2131230778;
			
			// aapt resource value: 0x7f080041
			public const int relativeLayout1 = 2131230785;
			
			// aapt resource value: 0x7f080015
			public const int replyButton = 2131230741;
			
			// aapt resource value: 0x7f080013
			public const int scrollView = 2131230739;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f08003d
			public const int scrollView1 = 2131230781;
			
			// aapt resource value: 0x7f08003c
			public const int sendMessageTxt = 2131230780;
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f080017
			public const int sendMessageTxt = 2131230743;
			
			// aapt resource value: 0x7f080037
			public const int sendMsgTest = 2131230775;
			
			// aapt resource value: 0x7f080016
			public const int spinner = 2131230742;
=======
			// aapt resource value: 0x7f080039
			public const int sendMsgTest = 2131230777;
			
			// aapt resource value: 0x7f08003b
			public const int spinner = 2131230779;
			
			// aapt resource value: 0x7f080001
			public const int standard = 2131230721;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f080014
			public const int textMsgView = 2131230740;
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f080020
			public const int textView1 = 2131230752;
=======
			// aapt resource value: 0x7f080022
			public const int textView1 = 2131230754;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f080040
			public const int textView2 = 2131230784;
			
			// aapt resource value: 0x7f080010
			public const int txtEmail = 2131230736;
			
<<<<<<< Updated upstream
			// aapt resource value: 0x7f08001b
			public const int txtOr = 2131230747;
=======
			// aapt resource value: 0x7f08001d
			public const int txtOr = 2131230749;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f080011
			public const int txtPassword = 2131230737;
			
			// aapt resource value: 0x7f08000d
			public const int txtPasswordSignIn = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int txtUserName = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int txtUserNameSignIn = 2131230732;
			
			// aapt resource value: 0x7f08004d
			public const int unblockViewProfileButton = 2131230797;
			
			// aapt resource value: 0x7f080049
			public const int upvoteButton = 2131230793;
			
			// aapt resource value: 0x7f080045
			public const int usernameviewprofile = 2131230789;
			
			// aapt resource value: 0x7f080002
			public const int wide = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_send_msg = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_sign_in = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_sign_up = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_view_msg = 2130903043;
			
			// aapt resource value: 0x7f030004
<<<<<<< Updated upstream
			public const int group_message = 2130903044;
=======
			public const int edit_profile = 2130903044;
>>>>>>> Stashed changes
			
			// aapt resource value: 0x7f030005
			public const int home_page = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int invite_request = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int location = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int message_spinner = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int messaging = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int msg_helper = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int nearby_users = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int view_profile = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int home_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050024
			public const int Email = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int Logout = 2131034149;
			
			// aapt resource value: 0x7f050022
			public const int Password = 2131034146;
			
			// aapt resource value: 0x7f050020
			public const int Sign_In = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int Sign_Up = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int Username = 2131034147;
			
			// aapt resource value: 0x7f05001f
			public const int app_name = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int auth_google_play_services_client_facebook_display_name = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int auth_google_play_services_client_google_display_name = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_api_unavailable_text = 2131034133;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_enable_button = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_enable_text = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_enable_title = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_install_text_phone = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_text_tablet = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_install_title = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_invalid_account_text = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_invalid_account_title = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_network_error_text = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_network_error_title = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_notification_ticker = 2131034112;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_restricted_profile_text = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_restricted_profile_title = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_sign_in_failed_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_sign_in_failed_title = 2131034134;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_unknown_issue = 2131034142;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_unsupported_text = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_unsupported_title = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_update_button = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_title = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_title = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_wear_update_text = 2131034122;
			
			// aapt resource value: 0x7f050014
			public const int common_open_on_phone = 2131034132;
			
			// aapt resource value: 0x7f05001a
			public const int common_signin_button_text = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int common_signin_button_text_long = 2131034139;
			
			// aapt resource value: 0x7f050027
			public const int delete_account = 2131034151;
			
			// aapt resource value: 0x7f050029
			public const int delete_question = 2131034153;
			
			// aapt resource value: 0x7f050026
			public const int edit_profile = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int logout_question = 2131034152;
			
			// aapt resource value: 0x7f05002b
			public const int no = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int yes = 2131034154;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
